export const NESO_PLAYERS = [
  { name: "Dado", strength: 5 },
  { name: "Aco Pop", strength: 5 },
  { name: "Andrej", strength: 5 },
  { name: "Lazukic", strength: 5 },
  { name: "Jovan", strength: 5 },
  { name: "Ringe", strength: 5 },
  { name: "Raso", strength: 5 },
  { name: "Ratomir", strength: 5 },
  { name: "Simo Prole", strength: 5 },
  { name: "Stefan Bozic", strength: 5 },
  { name: "Aco Bozic", strength: 5 },
  { name: "Nele", strength: 5 },
  { name: "Jovica", strength: 5 },
  { name: "Dejo", strength: 5 },
  { name: "Damjan", strength: 5 },
  { name: "Vladan L", strength: 5 },

  { name: "Bojan", strength: 4 },
  { name: "Borislav", strength: 4 },
  { name: "Darko Jovetic", strength: 4 },
  { name: "Dzigi", strength: 4 },
  { name: "Milenko", strength: 4 },
  { name: "Nebojsa V", strength: 4 },
  { name: "Nebojsa T", strength: 4 },
  { name: "Djordje", strength: 4 },
  { name: "Dragisa", strength: 4 },
  { name: "Pero", strength: 4 },
  { name: "Pedja", strength: 4 },
  { name: "Simo Manjic", strength: 4 },
  { name: "Slaven", strength: 4 },
  { name: "Slavomir", strength: 4 },
  { name: "Zoka", strength: 4 },
  { name: "Nemanja", strength: 4 },
];
